ktor:
    application:
        modules:
            - com.rabindradev.ApplicationKt.module
    deployment:
        port: 8081
    database:
        driver: "org.postgresql.Driver"
        url: "jdbc:postgresql://localhost:5432/myserverdb"
        user: "rabindra"
        password: "Rabindra@dev#8117"
        maxPoolSize: 10

jwt:
    domain: "https://jwt-provider-domain/"
    audience: "jwt-audience"
    realm: "Server app"